version: '3.1'

services:

    db:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: laravel
            MARIADB_PASSWORD: password
            MARIADB_DATABASE: flarum
        ports:
            - "3306:3306"
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
            - "1027:1025" # smtp server
            - "8027:8025" # web ui